# Generated by Django 2.1.2 on 2018-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fotografia', models.ImageField(default='img_folder/None/no-img.jpg', upload_to='img_mascotas/')),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('1', 'Rescatado'), ('2', 'Disponible'), ('3', 'Adoptado')], max_length=1)),
            ],
        ),
    ]
