# Generated by Django 2.1.2 on 2018-10-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0003_auto_20181023_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
    ]
