# Generated by Django 2.1.2 on 2018-10-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('numero_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('numero_region', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.CharField(max_length=30)),
                ('run', models.CharField(max_length=10)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('numero_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Ciudad')),
                ('numero_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Region')),
                ('tipo_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Tipo_Vivienda')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='numero_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Region'),
        ),
    ]
