# Generated by Django 2.1.2 on 2018-10-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='numero_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_vivienda',
            new_name='vivienda',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='run',
            new_name='rut'
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(max_length=30),
        ),
    ]
