# Generated by Django 2.1.2 on 2018-10-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20181017_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='vivienda',
            new_name='tipo_vivienda',
        ),
    ]
